### PR TITLE
I made the Note Splashes wiki page

### PR DESCRIPTION
**Pull request by KadePleaseHelpMe**
Let me know if I should change anything or be more professional

### CODE REVIEW

**Comment by NeeEoo** [comment]
Please upload the images as files in the format as note-splashes-1.png

and for the last updated use:
https://www.timestamp-converter.com/

**Comment by NeeEoo** [comment]
And also be a bit more professional, try to reference the writing style of the other pages

**Review by KadePleaseHelpMe — COMMENTED** [review]
Thanks for doing this! I was literally just got done rewriting the article as I'm seeing this so yeah hehe (rip tho)
I'm gonna try figuring out Dialogue Scripts after this
GG, Fraktis

**Comment by NeeEoo** [comment]
Could you quickly update the last updated? Using the link i provided above?

**Comment by KadePleaseHelpMe** [comment]
> Could you quickly update the last updated? Using the link i provided above?

Just did 👍

**Comment by NeeEoo** [comment]
You forgot to push it

**Comment by KadePleaseHelpMe** [comment]
> You forgot to push it

oh shit ok mb

**Comment by KadePleaseHelpMe** [comment]
k i think we're good to go-ish

**Comment by NeeEoo** [comment]
Yep you did

**Comment by KadePleaseHelpMe** [comment]
pog

**Pull request merged**
