### PR TITLE
Adding in some codename engine mods I found.

### PR DESCRIPTION
**Pull request by juney2008**
I didn't made these mods but I thought about adding in some mods that were made using Codename engine to the Codename engine website.

I might add in some mods that are planned to be moved over to Codename Engine too later on.

If you want to make any tweaks to the metadata of them, feel free to do so.

Current mods to add in:

Final Space | Death Sentence

FNF: Doomspire

FNF VS Sonic.EXE

Project: Chino's Chaos

SILLY ROBLOX MOD

Sunday's Desolation

### CODE REVIEW

**Comment by NeeEoo** [comment]
Also try to use the description for sunday and roblox. Usually the gray text above the description will be sufficient

**Comment by juney2008** [comment]
Alright, I'll go do that. Thanks for some advices. 👍

**Comment by NeeEoo** [comment]
For Final Space change it to hardcoded, since theres no codename modpack download
same for Doomspire, and SILLY ROBLOX and for sunday

I cant check the otherones, since slow internet, but i think they might not have modpack builds

**Comment by juney2008** [comment]
Oh, My bad. I'll go change the tags to hardcoded

**Pull request merged**
